CuaHangTheThao/Controllers/DoTheThaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CuaHangTheThao.Data;
using CuaHangTheThao.Models;

namespace CuaHangTheThao.Controllers
{
    public class DoTheThaosController : Controller
    {
        private readonly CuaHangTheThaoContext _context;

        public DoTheThaosController(CuaHangTheThaoContext context)
        {
            _context = context;
        }

        // GET: DoTheThaos
        public async Task<IActionResult> Index(string DoTheThaoGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from b in _context.DoTheThao
                                            orderby b.Genre
                                            select b.Genre;
            var DoTheThaos = from b in _context.DoTheThao
                        select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                DoTheThaos = DoTheThaos.Where(s => s.Title!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(DoTheThaoGenre))
            {
                DoTheThaos = DoTheThaos.Where(x => x.Genre == DoTheThaoGenre);
            }
            var DoTheThaoGenreVM = new DothethaoGenreViewModel
            {
                Genres = new SelectList(await
           genreQuery.Distinct().ToListAsync()),
                DoTheThaos = await DoTheThaos.ToListAsync()
            };
            return View(DoTheThaoGenreVM);
        }

        // GET: DoTheThaos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doTheThao = await _context.DoTheThao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doTheThao == null)
            {
                return NotFound();
            }

            return View(doTheThao);
        }

        // GET: DoTheThaos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DoTheThaos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] DoTheThao doTheThao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doTheThao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doTheThao);
        }

        // GET: DoTheThaos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doTheThao = await _context.DoTheThao.FindAsync(id);
            if (doTheThao == null)
            {
                return NotFound();
            }
            return View(doTheThao);
        }

        // POST: DoTheThaos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] DoTheThao doTheThao)
        {
            if (id != doTheThao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doTheThao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoTheThaoExists(doTheThao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doTheThao);
        }

        // GET: DoTheThaos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doTheThao = await _context.DoTheThao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doTheThao == null)
            {
                return NotFound();
            }

            return View(doTheThao);
        }

        // POST: DoTheThaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doTheThao = await _context.DoTheThao.FindAsync(id);
            _context.DoTheThao.Remove(doTheThao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoTheThaoExists(int id)
        {
            return _context.DoTheThao.Any(e => e.Id == id);
        }
    }
}

CuaHangTheThao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop Gia Dụng Hàng Thể Thao </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
      <link rel="stylesheet" href="~/css/Syte.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop Gia Dụng  Thể Thao </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Đồ  Bóng Đá</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DoTheThaos" asp-action="Index">Đặt Hàng</a> 
                        </li>
                    </ul>
                </div>
            </div><a href="https://localhost:44342/DoTheThaos/Create" class="login btn secondary stroke-outline" style="color: #00ff90; border: 5px solid ;background: #4800ff; "> </a>

            </div><a href="https://localhost:44342/DoTheThaos" class="login btn secondary stroke-outline" style="color: #4cff00; border: 5px solid ;background: #000000; "></a>

            <input id="skw" type="text" class="input-search" onkeyup="suggestSearch(event);" placeholder="Bạn tìm gì..." name="key" autocomplete="off" maxlength="100">
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>